name: Build & Push to Dockerhub

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Dockerhub
      run: echo ${{secrets.DOCKERHUB_ACCESS_TOKEN}} | docker login -u ${{vars.DOCKERHUB_USERNAME}} --password-stdin

    - name: Build production Docker image
      run: docker build -f deployment/docker/Dockerfile -t formio/pdf-libs:${{github.ref_name}} .

    - name: Build temp Docker image for testing (based off production image)
      run: docker build -f deployment/docker/Dockerfile-with-tests -t formio/pdf-libs:tmp --build-arg REF_NAME=${{github.ref_name}} .
    
    - name: Run tests on the temp image
      run: docker run formio/pdf-libs:tmp npm test

    - name: Push the production image
      run: docker push formio/pdf-libs:${{github.ref_name}}
    
    - name: Push latest
      run: |
        docker tag formio/pdf-libs:${{github.ref_name}} formio/pdf-libs:latest
        docker push formio/pdf-libs:latest
      if: ${{ !contains(github.ref_name, 'rc') && !contains(github.ref_name, 'test') }}
